### ISSUE TITLE
Turkish keyboard input problems

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#223] opened 2015-07-22 09:59 UTC
When i type this letters on turkish keyboard detected keys are listed below.

"ş"-"Ş", "ğ"-"Ğ" => "?"
"ı" => "y"
"İ" => "Y"

**Comment by ZaneDubya** [comment] 2015-08-05 00:26
@robertdeclaux Where do the incorrect characters appear? In the chat input box, or in the speech sent from the server?

**Comment by robertdeclaux** [comment] 2015-08-05 12:46
Both chat input box and from the server, i took the 3 lines of turkish keyboard input ss and the actual keyboard...
![ekran goruntusu 7](https://cloud.githubusercontent.com/assets/11157985/9085893/8aedfb08-3b89-11e5-993a-d146eb952507.png)
![ekran goruntusu 8](https://cloud.githubusercontent.com/assets/11157985/9085817/da7d0638-3b88-11e5-9bc5-5c02dd54b10d.png)
![ekran goruntusu 10](https://cloud.githubusercontent.com/assets/11157985/9085820/dc62aec6-3b88-11e5-9eb9-2438c05fe031.png)
![ekran goruntusu 11](https://cloud.githubusercontent.com/assets/11157985/9085826/dee15008-3b88-11e5-9f41-04daf35ccc4f.png)
![img_20150805_153648](https://cloud.githubusercontent.com/assets/11157985/9085827/e1273864-3b88-11e5-84c3-253408508e01.jpg)

**Comment by ZaneDubya** [comment] 2015-08-09 20:50
This is caused by the Client not knowing what codepage to use - it assumes english(1252?). Which is great, for all charsets that use latin characters. Not so great for different charsets like Turkish. 

I'm going to use this method to determine the current active codepage: http://stackoverflow.com/questions/3213728/how-to-get-code-page-by-language-culture

and then translate the codepage using an Encoding.

**Comment by ZaneDubya** [comment] 2015-08-14 15:31
@robertdeclaux Curious, what are the cpu/gpu stats on your laptop?

**Comment by fdsprod** [comment] 2015-08-14 16:12
Sounds like a perfect opportunity for a plugin ;)

**Comment by ZaneDubya** [comment] 2015-09-17 14:53
Last issue of M0.7 - let's get this finished!

**Comment by ZaneDubya** [comment] 2015-09-17 19:07
This should be fixed! If problems remain, please comment and reopen.

**Closed as completed by ZaneDubya** 2015-09-17 19:07 UTC
Labels: bug
