### ISSUE TITLE
UltimaXNA causing memory leak issue in Audiodg.exe

### ISSUE THREAD

**Issue by sean-thorburn** [ZaneDubya/UltimaXNA#319] opened 2015-08-30 09:40 UTC
After playing around with UltimaXNA yesterday, my Audiodg.exe is sitting on 5.2GB.

Might be something to look into.

Windows 7 with latest updates.
https://support.microsoft.com/en-us/kb/981013

**Comment by ZaneDubya** [comment] 2015-08-30 15:29
Very interesting. I'm only using XNA's basic audio functionality, so unless this is a bug with all XNA games, I can't see why it's happening at all.

A quick google search shows that this problem happens to many different games.

**Comment by ZaneDubya** [comment] 2015-08-31 13:08
Hi @sean-thorburn, I've reviewed a number of complaints about this same issue occurring concurrent with running many different games and apps. It appears to be an issue with interactions between windows' audio system and various audio drivers. Not many people have this issue, but a fair number seem to have won the bug lottery - and unfortunately, it appears that you are among them. Some people have had success with [this solution posted on answers.microsoft.com](http://answers.microsoft.com/en-us/windows/forum/all/audiodgexe-cpu-time-when-audio-system-inactive/4708582d-91ba-429c-a9b4-30ae4345575a), but some people say it doesn't work for them. I'm not sure what else I could suggest.

Unfortunately, if this is something that is happening to people running programs as diverse as VLC and Elder Scrolls Online, I don't think I'm going to be able to trouble shoot it, much less solve it. I've looked at UltimaXNA's audio code and I (1) only instantiate one buffer for each effect, (2) never play more than 32-64 sounds at a time, (3) always use the default xna ctors/play methods. I do not believe I'm doing anything on my end that would specifically cause this issue. I'm sorry it's happening to you.

**Comment by PatrikSamuelTauchim** [comment] 2015-08-31 13:24
@sean-thorburn I would do clean install of Windows 7 from original media first, maybe it is corrupted, infected or broken in some way. Especially if it is OEM preinstalled, preconfigured and filled with bloatware.

**Comment by jeffboulanger** [comment] 2015-08-31 17:07
@sean-thorburn Please install this hot fix and see if the problem is resolved https://support.microsoft.com/en-us/kb/981013

**Comment by fdsprod** [comment] 2015-08-31 19:12
@sean-thorburn Check that you have audio effects disabled, this was posted as a fix somewhere else.

**Comment by ZaneDubya** [comment] 2015-09-02 03:15
I'm closing this issue as unaddressable. I cannot replicate it on my end. I can't rule out that we're doing something wrong on our end, but @jeffboulanger has done some memory leak testing in the audio code and hasn't found anything obviously incorrect. Similarly, the fact that this bug is being caused by many different games and programs makes me think that it's not likely to be something we're doing. @sean-thorburn - good luck fixing it on your system!

**Closed as completed by ZaneDubya** 2015-09-02 03:15 UTC
Labels: bug

**Comment by sean-thorburn** [comment] 2015-09-02 04:32
Hi everyone,

Sorry I have not got back to you sooner.
I have never had this problem before, and I've been running my Windows 7 x64 install for over 2 years.

I have a Creative Sound Blaster X-Fi XtremeGamer.
I suspect it had something to do with me getting the client up and running, and testing on multiple versions of the Ultima Online client.

I did get some sound errors in the console in red due to missing files.
This may have had something to do with it.

Restarting of my Windows Sound Service fixed the problem.

**Comment by fdsprod** [comment] 2015-09-02 15:18
I personally did some memory leak testing and could not find a single issue with sound.  I did find issues with the journal and gave Zane the fixes but no sound issues.  If this continues to occur, I can walk you through how to use vs2015 to see if the leaks are in uxna or not.

**Comment by sean-thorburn** [comment] 2015-09-02 16:04
I'll give it another try some time and see if I can replicate the issue. Will post back here.

I am very excited about this project.

**Comment by ZaneDubya** [comment] 2015-09-02 16:21
@sean-thorburn So are we. Thank you for continuing to test it - I hope we can actually address your next bug :)
