### ISSUE TITLE
Hair is incorrectly hued.

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#85] opened 2015-03-31 06:26 UTC
Yesterday i tested after Fixing hues commit there was no problem, after the walking changes i have this strange problem.

![ekran goruntusu 38](https://cloud.githubusercontent.com/assets/11157985/6913339/800978d6-d787-11e4-83c9-d7858302faf3.png)

**Comment by robertdeclaux** [comment] 2015-03-31 07:43
And also the upper npc has some clothes on it.

**Comment by ZaneDubya** [comment] 2015-04-01 02:21
Have you tried checking out at an old commit and seeing if the problem was visible there?

Without knowing the hues/itemids of the objects these NPCs are wearing, I can't replicate it on my end.

**Comment by PatrikSamuelTauchim** [comment] 2015-04-01 06:59
Hello, I can confirm this bug in current master. Hue 1102 in classic client it is gray color, but in UltimaXNA looks like on screenshot. I compared this with like 10 days old version of UltimaXNA and no issue.

**Comment by robertdeclaux** [comment] 2015-04-01 07:20
Sorry i reported it wrong, https://github.com/ZaneDubya/UltimaXNA/commit/778951a19ac06e9d8dd4308f4557a42b26057d16 (Hues fix)
After this change this bug happens.

He wears
long beard, disp id 0203e, color 044e
long hair, disp id 0203c, color 044e
hooded robe, disp id 02687, color 0455

**Comment by Vodacek** [comment] 2015-04-01 07:23
all hues are strange after that change :)
 

---

**Comment by PatrikSamuelTauchim** [comment] 2015-04-01 07:23
Just tested, that same issue is at hueing mobiles and items at general, not just hairs. Bad hue is also visible in paperdoll.

**Comment by robertdeclaux** [comment] 2015-04-01 07:26
Reverting that change on Utility.cs of master branch fixes issue but we lose color match of default client.

**Comment by ZaneDubya** [comment] 2015-04-01 19:22
Okay, I believe this is fixed in branch hues-fix.

**Comment by robertdeclaux** [comment] 2015-04-01 22:07
fix confirmed.

**Comment by ZaneDubya** [comment] 2015-04-01 22:13
Thanks!

**Comment by PatrikSamuelTauchim** [comment] 2015-04-02 06:43
Are you sure? Experiencing still the same issue.

**Comment by Vodacek** [comment] 2015-04-02 06:45
mee to...
 

---

**Comment by robertdeclaux** [comment] 2015-04-02 06:54
It was fixed on my home pc, experiencing same issue in office too. May be the different hues.mul files causing this.

I have a hues.mul that updated on 26.07.2005 00:14, 260KB. I will check the hues file on my home pc when i arrive.

**Comment by PatrikSamuelTauchim** [comment] 2015-04-02 06:59
@robertdeclaux  I have hues.mul file from clean UO ML instalation
26/07/2005 12:14 260KB - probably the same

**Comment by ZaneDubya** [comment] 2015-04-02 14:09
I no longer see any inappropriately hued objects throughout the world. In particular, the two hues mentioned in this thread, hues 0x455, and 0x44e, render as expected. Can someone mention a specific hue that does not render as expected?

As an aside, my hues.mul file is the same as @Eskymak's

**Closed as completed** 2015-04-03 20:41 UTC
Labels: bug
