### ISSUE TITLE
Allshow command crashes client on sphereserver

### ISSUE THREAD

**Issue by robertdeclaux** [ZaneDubya/UltimaXNA#222] opened 2015-07-21 16:13 UTC
I was using this command as an benchmark on client, i'm not sure which update effected this feature but it was working great when we were recording this (https://www.youtube.com/watch?v=gUfpQkLBdzE). Now when i send allshow command client immediately crashes.
![allshow](https://cloud.githubusercontent.com/assets/11157985/8805917/931b0176-2fdc-11e5-89ee-68bdd3b0c5d8.PNG)

**Comment by ZaneDubya** [comment] 2015-07-25 16:48
@robertdeclaux I know what's causing this, but don't have an easy fix in mind. Give me a few days...

**Comment by ZaneDubya** [comment] 2015-08-04 01:20
@robertdeclaux Could we set up a debug session on your machine sometime this coming weekend?

**Comment by robertdeclaux** [comment] 2015-08-04 08:56
Of course let me know when you are free

**Comment by ZaneDubya** [comment] 2015-08-09 19:05
This is caused by SphereServer sending a mobile object before assigning the player's serial. It would be fixed by eliminating the PlayerMobile object altogether, replacing it with Mobile and using the IsClientEntity boolean to determine if we have a reference to the player's mobile.

**Comment by ZaneDubya** [comment] 2015-08-10 13:41
Fixed in 01dcfc4.

**Closed as completed by ZaneDubya** 2015-08-10 13:41 UTC
Labels: bug
