### ISSUE TITLE
Splitting item enhancements.

### ISSUE THREAD

**Issue by ZaneDubya** [ZaneDubya/UltimaXNA#164] opened 2015-05-27 18:31 UTC
The current implementation of splitting items works, but is not ideal.
- The 'split item' gump should acquire keyboard input on initialization.
- The 'split item' gump should be dragged by the mouse on initialization.

Any others?

**Comment by ZaneDubya** [comment] 2015-05-31 21:43
Item 1 completed in 614e0c8ae97a03ee943596d993e814bf5ea0d532

**Comment by ZaneDubya** [comment] 2015-05-31 23:16
Item 2 completed in e674abe4eeebb37acc2c0cd00cade2718914ec45

**Comment by PatrikSamuelTauchim** [comment] 2015-06-01 11:58
@ZaneDubya I am unable to split items that are placed on the ground. It works in container*. Tested with apples (amount 10) gold (amount 100) but i can drag and drop just whole stack. No "select amount" gump is shown. Is that bug or it is still not implemented?
- I am also unable to change/enter numeric value of amount other than starting with number "1", because it is not possible to remove/rewrite number "1" at amount selection gump. When i remove it, it appears again.

And small feature request, when "select amount" gump is shown, would be nice to remove default (max) numeric value from gump, whenever I start typing new value, so I dont have to remove default value first. I can save few backspace hits. ;-)

**Comment by ZaneDubya** [comment] 2015-06-01 12:24
Thanks @Eskymak, I'll take a look at those fixes!

**Comment by ZaneDubya** [comment] 2015-06-01 12:36
I don't want to remove the default numeric value. Instead, I'm going to make it so that when you start typing, you replace the default value. :)

**Comment by PatrikSamuelTauchim** [comment] 2015-06-01 12:49
@ZaneDubya Yep, thats exactly what I meant. ;)

**Comment by ZaneDubya** [comment] 2015-06-01 12:49
Ok, I think I've implemented all your suggestions. If I haven't, or you see anything else, let me know!

**Comment by PatrikSamuelTauchim** [comment] 2015-06-01 13:07
@ZaneDubya I think that splitting now works just fine.

Do we actually care about merging of items? Maybe the cause it's the same like for splitting, that it is not possible to merge same items on the ground by dragging one into another. (they are geting placed one on top of another) At container, it works.

**Comment by ZaneDubya** [comment] 2015-06-01 13:10
Do you know off hand if the legacy client allow you to merge items when the target of the merge is on the ground?

**Comment by PatrikSamuelTauchim** [comment] 2015-06-01 13:14
@ZaneDubya Yes, in legacy client it is possible. Drag one item into another same item on the ground and it gets merged. Just tested with apples. ;)

Only when item is placed on the same tile (not directly on the same item) or non-stackable, they should be placed on top of each other without merging.

**Comment by ZaneDubya** [comment] 2015-06-01 13:21
Thank you for looking at that! I'll get that implemented as well, probably this evening after work.

**Comment by ZaneDubya** [comment] 2015-06-03 21:39
@Eskymak should be fixed!

**Comment by PatrikSamuelTauchim** [comment] 2015-06-04 06:28
@ZaneDubya Can confirm it works! Thanks.

And one more thing, allow to move whole stack of items without showing "choose amount" gump, while holding Shift key pressed. Like classic client does.

Actually holding shift key results in emptying value from "choose amount" gump.

**Comment by ZaneDubya** [comment] 2015-06-04 12:29
@Eskymak Okay, implemented. Let me know if I did it incorrectly, and I'll take another look. Or if I'm missing anything else :)

**Comment by PatrikSamuelTauchim** [comment] 2015-06-04 13:02
@ZaneDubya Seems fine! I wish Microsoft developers work this way... :D

Just small, and I hope last detail, before this feature will be perfect:
- "choose amount" gump is sensitive to other than numeric input. (pressing any key clearing value from it) Probably only numeric value should make it clear/replace value. But that is really minor detail. ;)

Thanks!

**Comment by ZaneDubya** [comment] 2015-06-04 13:29
@Eskymak Haha, I know what you mean! But have you seen the latest preview builds of Windows 10? MS devs have made a TON of progress in the past two months, and it's about 99% bug free. Good enough to run as my main OS. I'm thinking/hoping MS is getting its act together!

Back on topic... :) I've allowed TextEntries to be numeric only, and enabled this functionality on the choose amount gump. Let me know if there's anything else!

**Comment by PatrikSamuelTauchim** [comment] 2015-06-04 13:42
@ZaneDubya Yeah, W10 is getting finally into good shape. And MS is also changing in some way.

Now it works as excpected. Thanks again!

**Comment by ZaneDubya** [comment] 2015-06-04 21:42
Thanks for the bug reports!!

**Closed as completed** 2015-06-04 21:42 UTC
Labels: feature
